services:
  db:
    image: mariadb:11
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  composer:
    profiles:
      - dev
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
    user: "${UID}:${GID}"
    working_dir: /app
    volumes:
      - ./:/app

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 50M

volumes:
  db_data: {}
